name = "drumpal-app"
main = "worker/index.js"
compatibility_date = "2024-09-23"
account_id = "b5b4fd1615fc03cb75076123542787ff"

[assets]
directory = "./dist"

[[d1_databases]]
binding = "DB"
database_name = "drumpal-db"
database_id = "47db1b61-933f-41e2-af98-d24a3142387f"
